In [ ]:
import numpy as np


# DAY 4 ✔

# Some functions in numpy

In [ ]:
#zeros
#ones
#identify
zero_arr=np.zeros(10)
print(zero_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#one
zero_arr=np.ones(10)
print(zero_arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
twodarray = np.array(np.ones(10), ndmin=2)
print(twodarray)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
array=np.zeros((2,2))
print(array)

[[0. 0.]
 [0. 0.]]


In [ ]:
array=np.ones((5,6))
print(array)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


### Identity Matrix eye() function

In [ ]:
array=np.eye((10))
print(array)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# Arithmetic Operation in Numpy Array

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr + 5)
print(arr - 5)
print(arr * 5)
print(arr / 5)

In [ ]:
# Perform all calc of two array
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1+arr2)
print(arr2-arr1)
print(arr1*arr2)
print(arr2/arr1)

[ 6  8 10 12]
[4 4 4 4]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]


### Calculation in 2d array using rand int in 2 array

In [ ]:
arr1 = np.random.randint(5,75,size=(3,4))
arr2 = np.random.randint(0,100,size=(3,4))
print(arr1)
print()
print(arr2)
print()
print(f"Addition: \n {arr1+arr2}")
print()
print(f"Substraction: \n {arr1-arr2}")
print()
print(f"Product: \n {arr1*arr2}")
print()
print(f"Division: \n {arr1/arr2}")

[[62 60  9 51]
 [19 41  9 29]
 [63 19 37  5]]

[[38 60 26 90]
 [28 22 58 48]
 [ 2  4  5 14]]

Addition: 
 [[100 120  35 141]
 [ 47  63  67  77]
 [ 65  23  42  19]]

Substraction: 
 [[ 24   0 -17 -39]
 [ -9  19 -49 -19]
 [ 61  15  32  -9]]

Product: 
 [[2356 3600  234 4590]
 [ 532  902  522 1392]
 [ 126   76  185   70]]

Division: 
 [[ 1.63157895  1.          0.34615385  0.56666667]
 [ 0.67857143  1.86363636  0.15517241  0.60416667]
 [31.5         4.75        7.4         0.35714286]]


# Slicing Operation
### Syntax: array_name[startPos:EndPos:Jump]

In [ ]:
arr=np.arange(10)
print(arr)
print(arr[3:8])   # YESMA CHAI HAMILE STARTING RW ENDING ASSIGN GARYAXUM
print(arr[5:])    # YESMA LAST SAMMA KO PRINT GARNE HUDA LAST KO POS NALEKHE HUNXA
print(arr[5:8])    # YESMA LAST SAMMA KO PRINT GARNE HUDA LAST KO POS NALEKHE HUNXA

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7]
[5 6 7 8 9]
[5 6 7]


In [ ]:
#Print even from 0 to 21
arr=np.arange(21)
print(arr)
print(arr[0:21:2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]


### Slice in 2D array

In [ ]:
array_2d = np.array([[1,2,3,4], [5,6,7,8]])
print(array_2d)

[[1 2 3]
 [5 6 7]]


In [ ]:
print(array_2d[0:1,1:3])

[[2 3]]


In [ ]:
arr2d = np.array([[9,8,7,6], [23,45,67,78]])
print(arr2d)

[[ 9  8  7  6]
 [23 45 67 78]]


In [ ]:
# Print 45 and 67
print(arr2d[1:,1:3])

[[45 67]]


In [ ]:
arrayy2d=np.array([[5,6,7,8],[3,4,6,7],[11,12,34,43]])
print(arrayy2d)

[[ 5  6  7  8]
 [ 3  4  6  7]
 [11 12 34 43]]


In [ ]:
print(arrayy2d[1:,0:2])

[[ 3  4]
 [11 12]]


# Shape and Reshaping in Numpy Array

### shape le row rw column return garxa

In [ ]:
array_1d=np.array([5,6,7,8])
array_1d.shape

(4,)

In [ ]:
array_2d=np.array([[5,6,7,8],[9,10,11,12]])
array_2d.shape

(2, 4)

### reshape in numpy changes dimension of array   --->>    arr_name.reshape(row,column) pass garne

In [ ]:
array_1d=np.array([1,2,3,4])
array_1d.reshape(2,2)

array([[1, 2],
       [3, 4]])

### Create Array of 12 element and reshape the array in 4 by 3 format

In [ ]:
arr=np.arange(12)
print(arr)
arr.reshape(4,3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# 2D To 1D
arrayy=np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])
print(arrayy.reshape(12))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Create two 2D matrix and perform multiply operation


In [ ]:
matrix1=np.matrix([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])
matrix2=np.matrix([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8]])
print(matrix1*matrix2)

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]
 [ 96 126 156]]
