In [49]:
print("Hello World")

Hello World


# LEARNING NUMPY

In [50]:


import numpy as np



# Creating array using numpy

In [51]:
arr = np.array([1,1])

In [52]:
print(arr)
print(type(arr))

[1 1]
<class 'numpy.ndarray'>


In [53]:
listt=[1,2,3,4,5]

In [54]:
print(listt)
print(type(listt))

[1, 2, 3, 4, 5]
<class 'list'>


### Generating 1-10 element in Numpy and List

In [55]:
list_range=[i for i in range(1,11)]

In [56]:
print(list_range)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [57]:
numpy_range=np.arange(1,11)
print(numpy_range)

[ 1  2  3  4  5  6  7  8  9 10]


### Array Iteration

In [58]:
numpy_iter=np.arange(1,11)
for i in range(0,10):
    print(numpy_iter[i])

1
2
3
4
5
6
7
8
9
10


### Convert List to Array using Numpy

In [59]:
list=["This","is","a","list",6,6,6]
arr=np.array(list)
print(arr)
print(type(arr))

['This' 'is' 'a' 'list' '6' '6' '6']
<class 'numpy.ndarray'>


### Convert Array To List

In [60]:
arr=np.array([1,2,3,4,5])
listt=arr.tolist()
print(arr)
print(listt)

[1 2 3 4 5]
[1, 2, 3, 4, 5]


# Creating 2D Array In Numpy

In [61]:
arr_2d = np.array([[1,2,3],[5,6,7]])
print(arr_2d)
print(arr_2d.ndim) #Dimension Check gareko


[[1 2 3]
 [5 6 7]]
2


# Using Random in Numpy

In [62]:
# rand     -->>   Generates a random value between 0 and 1.
# randn    -->>   Generates a random value close to 0.
# randint  -->>   Generates a random value within range specified.

# rand     -->>   Generates a random value between 0 and 1.

In [63]:
rand_arr = np.random.rand(10)    # Katiota chaiyeko specify garna sakinxa
print(rand_arr)

[0.23053225 0.88227028 0.98332309 0.85891654 0.28392073 0.20149608
 0.09875519 0.90456126 0.42058163 0.31886881]


In [70]:
# Print 2D Array Using Rand Function
rand2dArray = np.random.rand(5,4)
print(rand2dArray)

[[0.25133357 0.54772308 0.32627712 0.20071209]
 [0.88179056 0.84919662 0.29640103 0.69408909]
 [0.64654768 0.42737705 0.70325526 0.23008363]
 [0.89366031 0.806106   0.81150401 0.83337245]
 [0.40473445 0.23393118 0.06118479 0.15641259]]


# randn    -->>   Generates a random value close to 0.

In [42]:
randn_arr = np.random.randn(10)    # Katiota chaiyeko specify garna sakinxa
print(randn_arr)

[-0.80863879 -0.27616421  0.03819629 -3.69974929  0.56054676  0.76429739
 -0.47727047 -0.83087506 -0.59358426  0.63213573]


# randint  -->>   Generates a random value within range specified.

In [75]:
randint_arr = np.random.randint(2,10,5) #(start,stop,size)
print(randint_arr)

[9 5 5 4 2]


In [88]:
# 20 random number between 0 and 100 
randarr = np.random.randint(0,100,size=20)
randomArray = np.random.randint(0,100,20)
print(randarr)
print(randomArray)

[87 87 76 70 44 11 13 82 21 82 32  3 68 95  1 83 57 46 36 99]
[50 18 70 35 81 29 23 39  2 65 35 90 76 51 46 21 59 44  4 15]


In [85]:
# 2D Random Number Array 
randarr = np.random.randint(0,100,size=(3,3))
print(randarr)

[[ 7 62 85]
 [72 98 25]
 [72 63 23]]
